### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by cnyrr** [cnyrr/GoodbyeDPI_Configurator#1]
Remaining stuff to implement:

- [x] IP-ID
- [x] Blacklists
- [ ] Fake From Hex
- [ ] Fake From SNI
- [ ] Fake Gen
- [ ] Fake Resend
- [ ] ArgumentsToProfile method.

Requires fixes:

- [ ] ProfileToArguments

Other stuff:

- [ ] Merge dll
- [ ] Add a proper readme
